services:
  - type: web
    name: hirebotics-backend
    env: node
    region: oregon
    buildCommand: 'npm install'
    startCommand: 'node server.js'
    envVars:
      - key: OPENAI_API_KEY
        fromDatabase: OPENAI_API_KEY
